#!/bin/sh

[ -x /usr/sbin/httpd ] || exit 0

case "$1" in
    start)
        printf "Starting httpd: "
        start-stop-daemon -n httpd -S -x /usr/sbin/httpd
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        printf "Stopping httpd: "
        start-stop-daemon -n httpd -K
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac

exit 0

