#!/bin/sh
case "$1" in
    start)
        if vcgencmd otp_dump | grep 17:3020000a
            then echo heartbeat >/sys/class/leds/led1/trigger
            else exit 1
        fi
        ;;
    stop)
        exit 1
        ;;
    *)
        exit 1
        ;;
esac

exit 0

