#!/bin/sh

[ -x /usr/bin/treedys-controller ] || exit 0

exit 0

case "$1" in
    start)
        printf "Starting treedys-controller: "
        start-stop-daemon -b --make-pidfile -p /run/treedys-controller.pid -x /usr/bin/treedys-controller -S
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        printf "Stopping treedys-controller: "
        start-stop-daemon -p /run/treedys-controller.pid -K
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac

exit 0

